SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800

BALL_SIZE = 30
BALL_KILL_THRESH = BALL_SIZE // 2    # when do we kill the ball if it flies past the paddle
INITIAL_NUMBER_OF_BALLS = 1
INITIAL_BALL_SPEED = 6

POINTS_DISPLAY_Y = SCREEN_HEIGHT-50
POINTS_DISPLAY_X_MARGIN = 150

PADDLE_INITIAL_HEIGHT = 300
PADDLE_WIDTH = 30
PADDLE_MARGIN = 10

DEFAULT_OPPONENT_SPEED = 5
OPPONENT_SPEED_INCREASE = 1.2

HIT_ACCELERATION = 1
BALL_SPEED_INCREASE = 0.75

DEBUG = True
